Generate all responses with nested structs
shanbay/oapi-codegen pull request #2
Opened 2021-03-24 05:56 UTC by sljeff

1. Generate all responses with nested structs
2. remove binary

2021-03-24 08:34 UTC, fenngwd commented
Please squash commits into one.

2021-03-24 11:07 UTC, fenngwd commented on pkg/codegen/codegen.go
> +	if t == "" || t == "object" {
It means `type` field is an optional field?

2021-03-24 11:07 UTC, fenngwd commented on pkg/codegen/codegen.go
> +						JsonName: propertyName,
pName

2021-03-24 11:19 UTC, fenngwd commented on pkg/codegen/codegen.go
> +		schemaAndChildrenTypes, err := GenerateTypesFromSchemaRef(schemaOrRef, name)
element type's name same with allof type's name?

2021-03-24 11:19 UTC, fenngwd commented on pkg/codegen/codegen.go
> +		if ref != "" {
what if `ref == ""`

2021-03-24 11:19 UTC, fenngwd commented on pkg/codegen/codegen.go
> +		for _, p := range schemaAndChildrenTypes[0].Schema.Properties {
why should I merge other type's properties to first type?

2021-03-25 02:12 UTC, sljeff commented on pkg/codegen/codegen.go
> +	if t == "" || t == "object" {
表示它是个object，object需要做字段的遍历

2021-03-25 02:38 UTC, sljeff commented on pkg/codegen/codegen.go
> +						JsonName: propertyName,
（这边整段逻辑和原来代码里的GenerateGoSchema差不多）TypeDefinition里面的JsonName字段虽然叫这个名字但和json没有关系，在typedef.tmpl模板里只是影响了注释。影响某个property的注解json的参数是Property的JsonFieldName字段

2021-03-25 02:47 UTC, sljeff commented on pkg/codegen/codegen.go
> +		schemaAndChildrenTypes, err := GenerateTypesFromSchemaRef(schemaOrRef, name)
GenerateTypesFromSchemaRef返回的是个数组，第一项是这个schema本身的TypeDefinition，其余项是它包含的所有子对象的TypeDefinition。这个地方要把AllOf的对象一个一个生成TypeDifinition，目的是要把返回的第一项的Property都取出来组合（不会单独生成struct），其余项不变（会生成struct）。所以name是作为某个的AllOf对象的字段和子对象名字的prefix。

如果AllOf的两个对象有了名字相同的字段，确实会生成一样的名字，这个时候有错误要手动修复。

2021-03-25 02:51 UTC, sljeff commented on pkg/codegen/codegen.go
> +		if ref != "" {
```
    PagedTodayItemsWithSensesAndWordLog:
      allOf:
      - $ref: '#/components/schemas/Pagination'
      - type: object
        properties:
          objects:
            type: array
            items:
              type: object
              properties:
                vocabulary:
                  $ref: '#/components/schemas/VocabWithSenses'
                type_of:
                  type: string
                  description: 该单词类型
                  enum:
                  - NEW
                  - REVIEW
                  x-omitempty: false
            x-omitempty: false
```

这个AllOf表示PagedTodayItemsWithSensesAndWordLog这个对象想要组合一个ref过来的object和一个字面量写出来的object，这个时候遍历它的AllOf取到的第一个ref就不等于空字符串。这种情况会把这个第一项ref的对象不具名的嵌到struct里（组合字段）；而第二项那个会变成一个名字叫objects的字段。

2021-03-25 02:52 UTC, sljeff commented on pkg/codegen/codegen.go
> +		for _, p := range schemaAndChildrenTypes[0].Schema.Properties {
😁复制一下上面的：GenerateTypesFromSchemaRef返回的是个数组，第一项是这个schema本身的TypeDefinition，其余项是它包含的所有子对象的TypeDefinition。这个地方要把AllOf的对象一个一个生成TypeDifinition，目的是要把返回的第一项的Property都取出来组合（不会单独生成struct），其余项不变（会生成struct）。

2021-03-25 03:56 UTC, fenngwd requested changes

2021-03-25 03:56 UTC, fenngwd commented on pkg/codegen/codegen.go
> +						JsonName: propertyName,
那不应该叫 pName 吗？ propertyName 不是 typeName 吗？

2021-03-25 03:56 UTC, fenngwd commented on pkg/codegen/codegen.go
> +		schemaAndChildrenTypes, err := GenerateTypesFromSchemaRef(schemaOrRef, name)
这里的手动修复是指什么？改 gen 代码还是改 yaml 来避免？

2021-03-25 03:56 UTC, fenngwd commented on pkg/codegen/codegen.go
> +		if ref != "" {
这里想问的是 ref 为空的情况要不要考虑。不过现在看起来，后面的
`schemaAndChildrenTypes[0].Schema.RefType = refType` 好像 refType 为空也不影响

2021-03-25 03:56 UTC, fenngwd commented on pkg/codegen/codegen.go
> +	if t == "" || t == "object" {
意思是 type 为空也就是 type 为 object？

2021-03-25 05:27 UTC, sljeff commented on pkg/codegen/codegen.go
> +	if t == "" || t == "object" {
https://stackoverflow.com/questions/47374980/

如果没有type表示可以为任意类型，但是如果此时有properties字段（object类型专用）表示如果他是个object，那么应该包含这些字段。

2021-03-25 05:34 UTC, sljeff commented on pkg/codegen/codegen.go
> +						JsonName: propertyName,
比如一个结构是这样，AAA 有个子对象叫 BBB：
```
AAA {
    BBB {
        CCC string
    }
}
```

这个时候 pName 叫做 BBB，propertyName 叫做 AAABBB，此时生成的是：
```go
// AAA defines model for AAA
type AAA struct {
    BBB *AAABBB `json:"BBB"`
}

// AAABBB defines model for AAABBB
type AAABBB struct {
    CCC *string `json:"CCC"`
}
```

如果把 JsonName 改成 pName，那么得到的是注释变成了 `// AAABBB defines model for BBB`：
```go
// AAA defines model for AAA
type AAA struct {
    BBB *AAABBB `json:"BBB"`
}

// AAABBB defines model for BBB
type AAABBB struct {
    CCC *string `json:"CCC"`
}
```

2021-03-25 05:35 UTC, sljeff commented on pkg/codegen/codegen.go
> +		schemaAndChildrenTypes, err := GenerateTypesFromSchemaRef(schemaOrRef, name)
修改 yaml 来避免，相当于不能允许两个 allOf 包含相同的字段

2021-03-25 05:36 UTC, sljeff commented on pkg/codegen/codegen.go
> +		if ref != "" {
是的。RefType 不为空的时候匿名组合；为空的的时候嵌套对象。

2021-03-25 05:47 UTC, fenngwd commented on pkg/codegen/codegen.go
> +		schemaAndChildrenTypes, err := GenerateTypesFromSchemaRef(schemaOrRef, name)
那应该怎么提示用户不允许 allOf 的类型包含相同的内部字段

2021-03-25 05:50 UTC, fenngwd commented on pkg/codegen/codegen.go
> +		schemaAndChildrenTypes, err := GenerateTypesFromSchemaRef(schemaOrRef, name)
是否应该先校验如果有相同字段则报错？

2021-03-25 06:22 UTC, sljeff commented on pkg/codegen/codegen.go
> +		schemaAndChildrenTypes, err := GenerateTypesFromSchemaRef(schemaOrRef, name)
我提了个新的commit，这个Merge检测在原本生成request对象、schema、client时也是会被用到的，不知道为什么逻辑是 `&& !` 而不是 `||`，我把它修改了一下。

2021-03-25 06:37 UTC, fenngwd approved these changes

2021-03-25 06:37 UTC, fenngwd commented
LGTM

2021-03-25 06:38 UTC, merged